source 'https://rubygems.org'

# Web
gem 'rake'
gem 'rack'
gem 'puma'

# ROM / Database
gem 'rom-sql'
gem 'rom-changeset'
gem 'rom-repository'
gem 'sequel'
gem 'pg'

# dry-rb
gem 'dry-transaction'
gem 'dry-auto_inject'
gem 'dry-system'

# Hanami
gem 'hanami-controller'
gem 'hanami-router'

# Twist
gem 'rugged'
gem 'redcarpet'
gem 'nokogiri'
gem 'pygments.rb'
gem 'shrine'
gem 'babosa'
gem 'sidekiq'
gem 'bcrypt'
gem 'aws-sdk-s3'
gem 'oauth2'
gem 'octokit'
gem 'graphql'
gem 'dataloader'

group :dev do
  # Deployment
  gem 'capistrano'
  gem 'capistrano-chruby'
  gem 'capistrano-bundler'
end

group :dev, :test do
  gem 'pry'
  gem 'dotenv'
  gem 'rspec'
  gem 'database_cleaner'
end

group :test do
  gem 'rack-test'
  gem 'capybara'
  gem 'selenium-webdriver'
end
