source 'https://rubygems.org'

gem 'rake'
gem 'hanami',       '1.2.0.rc2'
gem 'hanami-model', '1.2.0.rc2'

gem 'pg'

gem 'bcrypt'
gem 'warden'

gem 'dry-container'
gem 'dry-auto_inject'
gem 'dry-transaction'

gem 'sidekiq'

gem 'rugged'
gem 'redcarpet'
gem 'pygments.rb'
gem 'nokogiri'

gem 'shrine'
gem 'aws-sdk-s3'

gem 'rollbar'

gem 'babosa'

gem 'graphql'
gem 'dataloader'

gem 'puma'

group :development do
  # Code reloading
  # See: http://hanamirb.org/guides/projects/code-reloading
  gem 'shotgun'

  gem 'hanami-webconsole'

  gem 'rubocop'

  gem 'capistrano'
  gem 'capistrano-chruby'
  gem 'capistrano-bundler'
  gem 'capistrano-hanami', require: false
end

group :test, :development do
  gem 'sass'
  gem 'pry'
end

group :test do
  gem 'rspec'
  gem 'capybara'
  gem 'database_cleaner'
  gem 'launchy'
end

gem 'dotenv', '~> 2.0'
