source 'https://rubygems.org'

gem 'twist-core', path: '../core', require: 'twist/core'

gem 'rake'
gem 'hanami',       '~> 1.2'

gem 'pg'

gem 'bcrypt'
gem 'warden'

gem 'sidekiq'

gem 'shrine'
gem 'aws-sdk-s3'

gem 'rollbar'

gem 'graphql', '~> 1.8'
gem 'dataloader'

gem 'puma'

gem 'jwt'

group :development do
  # Code reloading
  # See: http://hanamirb.org/guides/projects/code-reloading
  gem 'shotgun'

  gem 'hanami-webconsole'

  gem 'rubocop'

  gem 'capistrano'
  gem 'capistrano-chruby'
  gem 'capistrano-bundler'
  gem 'capistrano-hanami', require: false
end

group :test, :development do
  gem 'sass'
  gem 'pry'
end

group :test do
  gem 'rspec'
  gem 'capybara'
  gem 'database_cleaner'
  gem 'launchy'
end

gem 'dotenv', '~> 2.0'
