require 'bundler'
Bundler.setup

require_relative './config/boot'
require 'rom-repository'
require 'rom/sql/rake_task'

Rake.add_rakelib 'lib/tasks'

namespace :db do
  task :setup do
    ROM::SQL::RakeSupport.env = ROM.container(:sql, ENV['DATABASE_URL'], extensions: [:pg_json])
  end
end

task :environment do
  require './config/environment'
end

require "graphql/rake_task"

GraphQL::RakeTask.new(
  schema_name: "Twist::Web::GraphQL::Schema",
  directory: "../graphql",
  dependencies: [:environment]
)
