export const note: string
export const avatar: string
export const noteContainer: string
export const noteHeader: string
export const state: string
export const openState: string
export const closedState: string
export const noteBody: string
export const closeButton: string
export const openButton: string
export const buttons: string
